# Práctica Extra Sprint 3: Álgebra y Numpy

* Tanto si quieres ampliar tu destreza con Numpy como si necesitas recuperar el sprint, aquí tienes dos ejercicios que te permitirán conseguirlo.
* Descargalo en tu ordenador, hazlo en él y súbelo a tu repo personal si quieres o necesitas que cuente.


## PARTE I


<img src='https://i0.wp.com/contraste.info/desarrollo/wp-content/uploads/2015/04/Marsattacks_FichaCine_5566706.jpg?fit=260%2C180&ssl=1' width="300">
                                                                                                
Hemos sido invadidos por los extraterrestres. El Gobierno ha prohibido toda comunicación escrita en castellano. Para poder comunicarnos, debemos generar mensajes de hasta 9 letras, codificados conforme al siguiente diccionario:

```Python
{'A':8,
 'B':7,
 'C':5,
 'D':13,
 'E':9,
 'F':16,
 'G':18,
 'H':22,
 'I':4,
 'J':23,
 'K':11,
 'L':3,
 'M':21,
 'N':1,
 'O':6,
 'P':15,
 'Q':12,
 'R':19,
 'S':2,
 'T':14,
 'U':17,
 'V':20,
 'W':25,
 'X':24,
 'Y':10,
 'Z':26
}

```

Por ejemplo, el mensaje "MARCIANOS" lo codificaríamos como "21 8 19 5 4 8 1 6 2"

Para poder enviar mensajes, debemos introducir los dígitos en una matriz 3x3. En este ejemplo, la matriz sería:

$$A=\begin{bmatrix}21 & 8 & 19 \\ 5 & 4 & 8 \\ 1 & 6 & 2\end{bmatrix}$$

A continuación, hay que multiplicar por la izquierda esta matriz por otra proporcionada por el Gobierno:

$$C=\begin{bmatrix}2 & 0 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{bmatrix}$$

Por tanto, el mensaje resultante sería:

$$Z = CA=\begin{bmatrix}2 & 0 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{bmatrix}\begin{bmatrix}21 & 8 & 19 \\ 5 & 4 & 8 \\ 1 & 6 & 2\end{bmatrix}=\begin{bmatrix}43 & 22 & 40 \\ 22 & 14 & 21 \\ 5 & 4 & 8\end{bmatrix}$$

El receptor del mensaje deberá decodificarlo multiplicando la matriz $Z$ por la matriz $C^{-1}$ (por la izquierda):

$$C^{-1}Z=A$$

**SE PIDE:**
1. Implementa una función para enviar mensajes de 9 letras codificados
> 1.1 Genera los dígitos correspondientes al mensaje a partir del diccionario y guárdalo en una lista  
> 1.2 Haz un reshape de la lista para transformarlo en un array de numpy 3x3  
> 1.3 Genera la matriz $Z=CA$, que será el output de la función
2. Implementa una función para decodificar mensajes de 9 letras
> 2.1 Crea un nuevo diccionario, donde se inviertan las claves y los valores del original  
> 2.2 Realiza la operación $C^{-1}Z=A$ y convierte la matriz a un vector con el método `flatten()`  
> 2.3 Recorre los elementos del vector para generar el mensaje decodificado usando el diccionario creado en 2.1

Consejo: Antes de implementar la función, reproduce el ejemplo del enunciado. Cuando te funcione, encapsula tu código en funciones

In [3]:
import numpy as np

key_dict = {
    'A':8,
    'B':7,
    'C':5,
    'D':13,
    'E':9,
    'F':16,
    'G':18,
    'H':22,
    'I':4,
    'J':23,
    'K':11,
    'L':3,
    'M':21,
    'N':1,
    'O':6,
    'P':15,
    'Q':12,
    'R':19,
    'S':2,
    'T':14,
    'U':17,
    'V':20,
    'W':25,
    'X':24,
    'Y':10,
    'Z':26
}

In [102]:
def code_msg(original_msg, key_dict):
    msg = original_msg.upper().replace(' ', '')
    coded_list = []
    for char in msg:
        coded_list.append(key_dict[char])

    A = np.array(coded_list).reshape((3,3)) 
    C = np.array([[2,0,1], [1,0,1], [0,1,0]])
    Z = C.dot(A)
    return Z

def decode_msg(Z, key_dict):
    C = np.array([[2,0,1], [1,0,1], [0,1,0]])
    C_inv = np.linalg.inv(C).astype(np.int32)
    A = C_inv.dot(Z).flatten()
 
    msg = ''
    for n in A:
        msg += next((k for k, v in key_dict.items() if v == n))
    return msg

In [103]:
Z = code_msg('  marciaNoS', key_dict)
print('Mensaje codificado: \n', Z)

msg = decode_msg(Z, key_dict)
print('\nMensaje decodificado: \n', msg)

Mensaje codificado: 
 [[43 22 40]
 [22 14 21]
 [ 5  4  8]]

Mensaje decodificado: 
 MARCIANOS


## Parte II

En el álgebra de matrices, existen tres tipos de matrices de especial interés:

1. **Matriz diagonal**: Todos los elementos son 0 excepto los de la diagonal
    
    <img src='./img/diagonal.png' width = 200>

2. **Triangular superior**: Todos los elementos por encima de la diagonal son 0
    
    <img src='./img/upper.png' width = 200>

3. **Triangular inferior**: Todos los elementos por debajo de la diagonal son 0
    
    <img src='./img/lower.png' width = 200>

En numpy, las funciones `diag()`, `triu()` y `tril()` permiten hacer transformaciones de una matriz a cualquiera de las 3 anteriores

**CASO DE USO**


<img src='./img/bets.jpg' width=400>


En LaLiga se generan matrices como la siguiente, que indican la probabilidad estimada de cada resultado en un determinado partido:  

![SegmentLocal](./img/match_matrix.gif "segment")

Por ejemplo, la probabilidad estimada de que acaben 1-2 es del 3.37%  
La probabilidad de que acaben en empate sería la suma de la diagonal: $(0.0373+0.078+0.0409+0.0095+0.0012+0.0001)=16.7\%$

**SE PIDE**:

1. Implementa una función que reciba una matriz cuadrada nxn y devuelva un diccionario con la probabilidad de empate, victoria local y victoria visitante. Asegúrate de que la suma de estas tres probabilidades es próxima a 1.

2. Implementa otra función que transforme el diccionario con las probabilidades a un diccionario de cuotas redondeado a 2 decimales (la cuota la calculamos como la inversa de la probabilidad)

Prueba con esta matriz
$$ P=\begin{bmatrix}0.0373 & 0.082 & 0.013 & 0.004\\ 0.1504 & 0.098 & 0.0337 & 0.0097 \\
0.121 & 0.194 & 0.04 & 0.0118 \\ 0.088 &  0.076 & 0.032 & 0.0091\end{bmatrix}$$

In [105]:
P = np.array([[0.0373, 0.082, 0.013, 0.004], [0.1504, 0.098, 0.0337, 0.0097], [0.121, 0.194, 0.04, 0.0118], [0.088, 0.076, 0.032, 0.0091]])

In [155]:
def probability_dict(matrix):
     diagonal = np.diag(matrix)
     draw = np.sum(diagonal)
     di = np.diag_indices_from(matrix)
     
     lower = np.tril(matrix)
     lower[di] = 0 # hago 0 la diagonal, porque tril() incluye la diagonal
     local = np.sum(lower)
     
     upper = np.triu(matrix)
     upper[di] = 0 # hago 0 la diagonal, porque triu() incluye la diagonal
     visitor = np.sum(upper)
     
     p_dict = {
     'Empate': draw * 100,
     'Victoria local': local * 100,
     'Victoria visitante': visitor * 100,
     'Comprobación probabilidad': draw + local + visitor
     }
     
     return p_dict
 

In [156]:
probability_dict(P)

{'Empate': 18.44,
 'Victoria local': 66.14,
 'Victoria visitante': 15.42,
 'Comprobación probabilidad': 1.0}

In [165]:
def odds_dict(p_dict):
    o_dict = {key: np.round((1 / (value/100)), 2) for key, value in p_dict.items() if key != 'Comprobación probabilidad'}
    return o_dict

In [168]:
p_dict = probability_dict(P)
odds_dict(p_dict)

{'Empate': 5.42, 'Victoria local': 1.51, 'Victoria visitante': 6.49}